### ISSUE TITLE
trained CLIP weights

### ISSUE THREAD

**Issue by Wilsonwangs** [tommarvoloriddle/SLIP#11]
hello：for this code, where is the  trained CLIP weights

model = CLIPModel().to(device)
model.load_state_dict(torch.load('<path to trained CLIP weights eg:TrainL_Metric: 0.3710_ValidL_Metric: 0.7791_Epoch_99.pt>'))

**Comment by tommarvoloriddle** [comment]
Since weights exceed the file size limit on GitHub, we couldn't upload.
